supergraph:
  listen: 127.0.0.1:5000
  course:
    schema:
      subgraph_url: http://localhost:7217/graphql
  course:
    schema:
      graphref: Course-u961x8@current
      subgraph: course
include_subgraph_errors:
  all: true
telemetry:
  instrumentation:
    spans:
      mode: spec_compliant